name: lunasea
description: Self Hosted Manager
version: 3.1.0+310002
publish_to: 'none'
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  connectivity: ^0.4.9
  convert: ^2.1.1
  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  encrypt: ^4.0.2
  expandable: ^4.1.4
  file_picker: ^1.12.0
  flare_flutter: ^2.0.5
  flash: ^1.3.1
  flutter:
    sdk: flutter
  flutter_advanced_networkimage: ^0.7.0
  flutter_sticky_header: ^0.4.2
  f_logs: ^1.2.2
  google_fonts: ^1.1.0
  google_nav_bar: ^2.2.0
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  in_app_purchase: ^0.3.4+1
  intl: ^0.16.1
  package_info: ^0.4.1
  path_provider: ^1.6.11
  percent_indicator: ^2.1.5
  permission_handler: ^5.0.1+1
  provider: ^4.3.1
  stack_trace: ^1.9.5
  table_calendar: ^2.2.3
  tuple: ^1.0.3
  url_launcher: ^5.5.0
  xml_parser: ^0.1.2
  # LunaTools Packages
  wake_on_lan: ^1.1.0+6

dev_dependencies:
  build_runner: ^1.10.0
  flutter_launcher_icons: ^0.7.5
  flutter_native_splash: ^0.1.9
  hive_generator: ^0.7.0+2

flutter:
  uses-material-design: true
  assets:
    # Colors
    - assets/images/colors/
    # Automation
    - assets/images/lidarr/
    - assets/images/radarr/
    - assets/images/sonarr/
    # Services
    - assets/images/services/
    # Branding
    - assets/branding/icon.png
    # Rive Animations
    - assets/rive/coding.flr
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/branding/icon.png"
  adaptive_icon_background: "#32323E"
  adaptive_icon_foreground: "assets/branding/icon_adaptive.png"

flutter_native_splash:
  image: "assets/branding/splash.png"
  color: "#32323E"
