name: lunasea
description: Self-Hosted Controller
version: 5.0.0+50000013
publish_to: 'none'
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  badges: ^1.2.0
  cloud_firestore: ^1.0.1
  connectivity_plus: ^1.0.0
  convert: ^3.0.0
  dio: ^4.0.0-beta7
  easy_localization: ^3.0.0
  encrypt: ^5.0.0-beta.1
  expandable: ^4.1.4
  file_picker: ^3.0.0
  firebase_analytics: ^7.1.1
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  firebase_crashlytics: ^1.0.0
  firebase_messaging: ^9.0.0
  firebase_storage: ^8.0.0
  flash: ^1.5.0
  fluro: ^2.0.3
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.0.0
  flutter_sticky_header: ^0.5.0
  fl_chart: ^0.20.1
  f_logs: ^1.3.0-alpha-02
  google_nav_bar: ^4.0.2
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  in_app_purchase: ^0.5.1
  infinite_scroll_pagination: ^3.0.1
  intl: ^0.17.0
  modal_bottom_sheet: ^2.0.0
  network_info_plus: ^1.0.0
  package_info: ^2.0.0
  path_provider: ^2.0.1
  percent_indicator: ^2.1.9+1
  provider: ^5.0.0
  quick_actions: ^0.5.0
  share_plus: ^2.0.0
  stack_trace: ^1.10.0
  supercharged: ^2.0.0
  table_calendar: ^2.3.3
  tuple: ^1.0.3
  url_launcher: ^6.0.2
  uuid: ^3.0.1
  xml: ^5.0.2
  # Comet.Tools Packages
  radarr: ^2.0.0-pre.1
  sonarr: ^2.0.0-pre.1
  tautulli: ^2.0.0-pre.2
  wake_on_lan: ^2.0.1

dependency_overrides:
  intl: ^0.17.0
  path_provider: ^2.0.1

dev_dependencies:
  analyzer: ^1.1.0
  build_runner: ^1.11.5
  hive_generator: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    # System Assets
    - assets/changelog.json
    - assets/localization/
    - assets/branding/
    # Other
    - assets/images/colors/
    - assets/images/lidarr/
    - assets/images/radarr/
    - assets/images/sonarr/
    - assets/images/tautulli/
    - assets/images/services/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/branding/icon.png"
  adaptive_icon_background: "#32323E"
  adaptive_icon_foreground: "assets/branding/icon_adaptive.png"

flutter_native_splash:
  image: "assets/branding/splash.png"
  color: "#32323E"

scripts: derry.yaml
