name: lunasea
description: iOS Usenet Manager
version: 2.0.0+88

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  bottom_navy_bar: ^5.3.2
  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  encrypt: ^4.0.0
  file_picker: ^1.5.0+2
  flushbar: ^1.9.1
  flutter:
    sdk: flutter
  flutter_advanced_networkimage: ^0.7.0
  flutter_sticky_header: ^0.4.2
  f_logs: ^1.2.2
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  http: ^0.12.0+4
  intl: ^0.16.1
  package_info: ^0.4.0+16
  path_provider: ^1.6.5
  percent_indicator: ^2.1.1+1
  permission_handler: ^4.4.0+hotfix.2
  provider: ^4.0.4
  stack_trace: ^1.9.3
  table_calendar: ^2.2.3
  tuple: ^1.0.3
  url_launcher: ^5.4.2
  validators: ^2.0.0+1
  xml_parser: ^0.1.2

dev_dependencies:
  build_runner: ^1.8.0
  dapackages: ^1.1.1
  flutter_launcher_icons: ^0.7.4
  flutter_native_splash: ^0.1.9
  hive_generator: ^0.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/accent_color.png
    - assets/images/secondary_color.png
    - assets/images/lidarr/noalbumart.png
    - assets/images/lidarr/noartistposter.png
    - assets/images/radarr/nomovieposter.png
    - assets/images/sonarr/noseriesposter.png
    - assets/images/services/imdb.png
    - assets/images/services/youtube.png
    - assets/images/services/tvmaze.png
    - assets/images/services/thetvdb.png
    - assets/images/services/themoviedb.png
    - assets/images/services/discogs.png
    - assets/images/services/bandsintown.png
    - assets/images/services/lastfm.png
    - assets/icon/icon.png
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf

flutter_icons:
  android: false
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  image: "assets/icon/icon.png"
  color: "#32323E"
  android: false
